Backend start
deep-skill/silver-api pull request #1
Opened 2023-06-19 23:11 UTC by brunofoster03

Created initial backend configuration with Node.JS and Express.JS. With app and database configuration, sequelize models and routes configuration

2023-06-21 12:09 UTC, manduinca requested changes
I leaved some comments.

2023-06-21 12:09 UTC, manduinca commented on src/models/Extra.js
> +  sequelize.define('Extra', {
Maybe a better name can be: `TripAdditionalCharges`

2023-06-21 12:09 UTC, manduinca commented on src/database.js
> +const RolModel = require('./models/Rol.js')
Role?

2023-06-21 12:09 UTC, manduinca commented on src/database.js
> +const EnterpriceModel = require('./models/Enterprice.js')
Enterprise?

2023-06-21 12:09 UTC, manduinca commented on src/database.js
Please review names. I think we are missing someone changes.

2023-06-21 12:09 UTC, manduinca commented on .vscode/settings.json
Please don't push it to repository. You can add `.vscode` line to gitignore file.

2023-06-21 20:33 UTC, manduinca requested changes
Please change rol to role.

2023-06-21 20:33 UTC, manduinca commented on src/models/Rol.js
Please don't forget this file. Role.

2023-06-21 21:18 UTC, martinalturria submitted a review, later dismissed

2023-06-21 22:42 UTC, manduinca requested changes

2023-06-21 22:42 UTC, manduinca commented on src/models/Rol.js
I think you forget this file, please delete it.

2023-06-22 13:17 UTC, manduinca approved these changes
LGTM!

2023-06-22 13:34 UTC, martinalturria approved these changes
LGTM

2023-06-22 13:34 UTC, merged